services:
  postgres:
    image: postgres:17
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tender-hack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tender-hack"]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.29.0
    container_name: liquibase
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://postgres:5432/tender-hack
      - LIQUIBASE_COMMAND_USERNAME=postgres
      - LIQUIBASE_COMMAND_PASSWORD=postgres
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=changelog_master.yml
      - LIQUIBASE_SEARCH_PATH=/changelog
    volumes:
      - ./db/migrations:/changelog
    command: update

volumes:
  postgres_data: